spring.application.name=Banking_System

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.profiles.active=local

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Application information
info.app.name=Banking System
info.app.description=Banking Management System API
info.app.version=1.0.0
management.info.env.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.BankingSystem.Banking_System=DEBUG